import csv
import os
import pandas as pd

directory = "C:/Users/yeahd/Documents/Python_Projects/GPUNIT/Pulls/"
gpus = []
# Put all GPUs from the scraper output files into a single list
for file in os.listdir(directory): #Iterate through files
    with open(directory+file, mode='r', encoding='utf-8', errors='ignore') as thing:
        csvfile = csv.reader(thing, delimiter=',', skipinitialspace=True) #skipinitialspace=True rmoves leading and trailing whitespace from each field
        next(csvfile) #Skip header row
        for item in csvfile:
            gpus.append(item)

# Pull in the GPUs in the "cleaned" file to allow for removal of the scraper files
with open("C:/Users/yeahd/Documents/Python_Projects/GPUNIT/GPU Cleaned.csv", mode='r', encoding='utf-8', errors='ignore') as cleanfile:
    csvclean = csv.reader(cleanfile, delimiter=',', skipinitialspace=True) #skipinitialspace=True rmoves leading and trailing whitespace from each field
    next(csvclean) #Skip header row
    for cleanitem in csvclean:
        gpus.append(cleanitem)

csv_file = "GPU Sale Price.csv" #keep all entries in this file. GPU Cleaned will remove dups.
with open(csv_file, mode="w", encoding="utf-8", newline="") as csvfile:
    fieldnames = ["ID", "Type", "Sale Date", "Details", "Price",
                  "Seller","Shipping"]
    writer = csv.writer(csvfile)
    writer.writerow(fieldnames)
    for gpu in gpus:
        writer.writerow(gpu)

# Read the CSV file into a DataFrame
df = pd.read_csv(csv_file)
#Print number of rows before removing dups
print(len(df.index))
# Drop duplicate rows
df_cleaned = df.drop_duplicates()
# Ensure we have a mutable copy before modifying columns (avoids SettingWithCopyWarning)
df_cleaned = df_cleaned.copy()
#print number of rows after removing dups
print(len(df_cleaned.index))
# Save the cleaned DataFrame to a new CSV file
output_file = "GPU Cleaned.csv"
df_cleaned.to_csv(output_file, index=False)

print(f"Duplicates removed. Cleaned file saved as '{output_file}'.")

# --- Update the Firefox extension data file --------------------------------------------------
# Compute average sale prices per GPU type using the last 90 days of data.
# LOOKS LIKE THERE ARE SOME ERRORS HERE.
df_cleaned["Sale Date"] = pd.to_datetime(df_cleaned["Sale Date"], errors="coerce")
cutoff = pd.Timestamp.today() - pd.Timedelta(days=90)
recent = df_cleaned[df_cleaned["Sale Date"] >= cutoff]
if recent.empty:
    # Fallback to all rows if the date parsing/filtering yields no recent data
    recent = df_cleaned
    print("No recent sales in the last 90 days; using all data for averages.")
else:
    print(f"Using {len(recent)} sales from the last 90 days to compute averages.")

# Calculate per-GPU-type average prices for "Used" items (Details != "Parts")
used_df = recent[recent["Details"].str.lower() != "parts"]
used_averages = used_df.groupby("Type")["Price"].mean().round(2).sort_index()
used_volumes = used_df.groupby("Type").size().sort_index()

# Calculate per-GPU-type average prices for "Parts" items (Details == "Parts")
parts_df = recent[recent["Details"].str.lower() == "parts"]
parts_averages = parts_df.groupby("Type")["Price"].mean().round(2).sort_index()
parts_volumes = parts_df.groupby("Type").size().sort_index()

# Get all unique GPU types
all_gpu_types = sorted(set(used_averages.index) | set(parts_averages.index))

# Write the JS file used by the Firefox extension for price recommendations
data_js_path = os.path.join(os.path.dirname(__file__), "firefox_extension", "data.js")
with open(data_js_path, "w", encoding="utf-8", newline="\n") as jsfile:
    jsfile.write("// Auto-generated by condense.py. Do not edit manually.\n")
    jsfile.write(f"// Generated on {pd.Timestamp.today().strftime('%Y-%m-%d')}\n")
    jsfile.write("const gpuAverages = {\n")
    for gpu_type in all_gpu_types:
        key = str(gpu_type).replace("'", "\\'")
        used_avg = used_averages.get(gpu_type, 0)
        parts_avg = parts_averages.get(gpu_type, 0)
        used_vol = used_volumes.get(gpu_type, 0)
        parts_vol = parts_volumes.get(gpu_type, 0)
        jsfile.write(f"  '{key}': {{ used: {used_avg}, parts: {parts_avg}, usedVol: {used_vol}, partsVol: {parts_vol} }},\n")
    jsfile.write("};\n")

print(f"Updated '{data_js_path}' with {len(all_gpu_types)} GPU types.")
print(f"  Used prices: {len(used_averages)} GPU types")
print(f"  Parts prices: {len(parts_averages)} GPU types")
